apiVersion: v1
kind: Pod
metadata:
  name: gop-fileserver
  labels:
    app: gop-fileserver
spec:
  volumes:
    - name: data-store
      persistentVolumeClaim:
        claimName: data-pvc
  containers:
  - name: gop-fileserver
    image: kodekloud/fileserver
    volumeMounts:
      - name: data-store
        mountPath:  /web
  
    