apiVersion: v1
kind: Service
metadata:
  name: drupal-service
spec:
  selector:
    app: drupal
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30096
  type: NodePort