apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  namespace: vote-ns
  labels:
    name: result-deployment
    app: result-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
       app: result-deployment
  template:
    metadata:
      labels:
        app: result-deployment
    spec:
      containers:
      - name: result-deployment
        image: kodekloud/examplevotingapp_result:before
    
    
