apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  namespace: vote-ns
  labels:
    name: vote-deployment
    app: vote-deployment
spec:
  replicas: 1
  #serviceName: mariab-service
  selector:
    matchLabels:
       app: vote-deployment
  template:
    metadata:
      labels:
        app: vote-deployment
    spec:
      containers:
      - name: vote-deployment
        image: kodekloud/examplevotingapp_vote:before
    
    
