apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: vote-ns
  labels:
    name: worker
    app: worker
spec:
  replicas: 1
  #serviceName: mariab-service
  selector:
    matchLabels:
       app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: kodekloud/examplevotingapp_worker
    
    
