apiVersion: v1
kind: Service
metadata:
  name: jekyll
  namespace: development
spec:
  selector:
    run: jekyll
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 4000
      nodePort: 30097
  type: NodePort
   