apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name:  developer-rolebinding
  namespace: development
subjects:
- kind: User
  name: drogo # "name" is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: developer-role
  apiGroup: rbac.authorization.k8s.io